# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oolong
email: jalaunder@gmail.com
baseurl: "/oolong" # the subpath of your site
author: YtnomSnrub
encoding: utf-8

# Build settings
markdown: kramdown
# Google Analytics
google_analytics: UA-105356258-6

defaults:
  - scope:
      path: "assets"
    values:
      resource: true
  - scope:
      path: "assets/data/raw"
    values:
      resource: false
  - scope:
      path: "assets/data/presets"
    values:
      preset: true
  - scope:
      path: "assets/data/presets/cities"
    values:
      preset_cities: true
  - scope:
      path: "assets/data/presets/names"
    values:
      preset_names: true
  - scope:
      path: "assets/data/presets/words"
    values:
      preset_words: true

github: [metadata]
